# Generated by Django 3.1.14 on 2023-02-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20230202_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='endurance',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='health',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='protection',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='attack',
            field=models.IntegerField(blank=True, null=True, verbose_name='Атака'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='endurance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выносливость'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='health',
            field=models.IntegerField(blank=True, null=True, verbose_name='Здоровье'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='protection',
            field=models.IntegerField(blank=True, null=True, verbose_name='Защита'),
        ),
    ]
